"""
siren.py
Continuous Implicit Manifold generated via Factorised Hypernetwork.
Bypasses the O(H^2) parameter bottleneck of standard SIREN weight generation.
"""
import torch
import torch.nn as nn
import math
from config import NETWORK

class FactorisedHypernetwork(nn.Module):
    """
    Maps the global latent vector to SIREN weights via low-rank factorization.
    """
    def __init__(self):
        super().__init__()
        self.D = NETWORK.latent_dim_D
        self.H = NETWORK.siren_hidden_H
        self.R = NETWORK.hypernet_rank_R
        
        # Low-rank basis matrix generators
        self.net_A = nn.Linear(self.D, self.H * self.R)
        self.net_B = nn.Linear(self.D, self.R * self.H)
        
    def forward(self, h_global: torch.Tensor) -> torch.Tensor:
        """
        Reconstructs the full SIREN hidden weight matrix: W = A x B
        """
        A = self.net_A(h_global).view(-1, self.H, self.R)
        B = self.net_B(h_global).view(-1, self.R, self.H)
        W_siren = torch.bmm(A, B)
        return W_siren

class SIREN(nn.Module):
    """
    Sinusoidal Representation Network for continuous coordinate mapping.
    """
    def __init__(self):
        super().__init__()
        self.H = NETWORK.siren_hidden_H
        self.omega_0 = NETWORK.siren_omega_0
        
        # Coordinate Input Layer (x, y) -> Hidden
        self.layer_in = nn.Linear(2, self.H)
        
        # Output Layer: Hidden -> Scalar Pre-Density
        self.layer_out = nn.Linear(self.H, 1)
        
    def forward(self, x: torch.Tensor, W_hidden: torch.Tensor) -> torch.Tensor:
        """
        Maps Cartesian coordinates to raw neural density bounded by a sigmoid.
        """
        # First layer with sine activation and spatial frequency scaling
        out = torch.sin(self.omega_0 * self.layer_in(x))
        
        # Dynamic hidden layer utilizing weights generated by the Hypernetwork
        # Handling batch matrix multiplication for coordinate grids
        out = torch.bmm(out.unsqueeze(1), W_hidden.transpose(1, 2)).squeeze(1)
        out = torch.sin(self.omega_0 * out)
        
        # Output bounded to (0, 1) pre-density field
        rho_tilde = torch.sigmoid(self.layer_out(out))
        return rho_tilde